### ISSUE TITLE
Problem with `Python 3.12`

### ISSUE THREAD

**Issue by gitdevjin** [HTSagara/readme_genie#14]
When I ran the tool, I got this error message. I googled it and asked ChatGPT. They say the module `distutils` is no longer supported from `Python 3.12` or later versions. I think it would be great if your tool is compatible with other `Python` versions, instead of being compatible with certain versions.

<img width="1219" alt="Screenshot 2024-10-02 at 12 32 27 AM" src="https://github.com/user-attachments/assets/86b37dfe-70fa-4af9-b72f-519f69ea4eee">

**Comment by HTSagara** [comment]
Can you try to run it using Docker? I just implemented it.
