### ISSUE TITLE
Log messages and errors go to stdout instead of stderr

### ISSUE THREAD

**Issue by mulla028** [HTSagara/readme_genie#3]
### Summary

**Currently, the program prints all errors and exceptions to stdout. Best practices recommend sending error messages to stderr, allowing proper logging and separation of standard output (such as normal program results) from error output. This is important when running programs in production, debugging, or piping output to other programs.**

### Suggested Steps

1. Import `sys` Module:
<tab>Add `import sys` to access the stderr stream
2. Redirect Exception Messages to `stderr`:
   - In the try-except block, modify the `print` statement so that errors are sent to `sys.stderr` instead of `sys.stdout`
   
   Replace: 
      ```python
      print(f"An unexpected error occured: {e}")
      ```
   With:
      ```python
      print(f"An unexpected error occured: {e}", file=sys.stderr)
      ```
### Conclusion

**Redirecting error messages to `stderr` improves the program's robustness and adheres to best practices for error handling. It makes debugging and logging easier, especially when redirecting output streams. Implementing the changes will ensure that error output is properly separated from normal output, leading to better error management.**

**Comment by HTSagara** [comment]
Thanks for the issues, it helped me a lot to improve my code
